### ISSUE TITLE
Relict iptables rules

### ISSUE THREAD

**Issue by dvapelnik** [tfoote/squid-in-a-can#3]
I have get errors with using and deploying this tool for caching content for dockerized applications, but something was wrong and I killed all containers. Exactly kill. After this my containers cannot retrieve data from outer web via 80th port. I know that is reasons of the `iptables`'s rules, but I can't fix this.
I have `iptables`'s output exactly like in this your [comment](https://github.com/jpetazzo/squid-in-a-can/issues/8#issuecomment-69103392). Firstly I need to fix a problem with access to wide web from docker containers. How can I do that?

**Comment by tfoote** [comment]
If the iptables container goes down without cleanup it will leave the iptables rules. 

To cleanup run this command; https://github.com/tfoote/squid-in-a-can/blob/master/iptables_docker/deploy.py#L32

It evalutates to: 
`iptables -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to 3129 -w`

**Comment by tfoote** [comment]
PS please file tickets upstream on https://github.com/jpetazzo/squid-in-a-can this is just my workspace for testing before submitting upstream.
